# start workflow on push or pull request

name: Deploy
env:
    ENVIRONMENT_NAME: prod
on:
    workflow_dispatch:
        inputs:
            force_deploy:
                description: 'Force Deploy?'
                required: true
                type: boolean

jobs:
    deploy:
        environment: prod
        runs-on: ubuntu-latest
        steps:
            # build a docker image
            - name: checkout code from repository
              uses: actions/checkout@v2
            - name: Build Docker Image
              env: 
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                docker build --build-arg GH_TOKEN="${GH_TOKEN}" -t docker-go-app:latest -f Dockerfile .
                docker run docker-go-app:latest -env prod
