# start workflow on push or pull request

name: Deploy

on:
    workflow_dispatch:
        inputs:
            force_deploy:
                description: 'Force Deploy?'
                required: true
                type: boolean

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # build a docker image
            - name: checkout code from repository
              uses: actions/checkout@v2
            - name: display secrets
              run: echo "${{ secrets.GH_TOKEN }}"
            - name: Build Docker Image
              run: docker build --progress=plain --no-cache --build-arg GH_TOKEN="${{ secrets.GH_TOKEN }}" -t docker-go-app:latest -f Dockerfile .
            - name: Run Docker container
              run: docker run docker-go-app:latest
